import Head from "next/head";
import Footer from "../Components/footer";
import Link from "next/link";
import Navbar from "../Components/navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Letter Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.body}>
        <Link href={"http://localhost:3000/login"}>
          <button className={styles.startButton}>Continue & Get Started</button>
        </Link>
      </div>
      <Footer />
    </div>
  );
}
